### ISSUE TITLE
Shortened PCB

### ISSUE THREAD

**Issue by SaLuci** [APatenaude/rc-diy-remote-display-esp32#1]
Hey, 
Thank you for creating this repo.
Just one question:
How did you shorten the PCB? Did you just cut off the excess PCB?

**Comment by APatenaude** [comment]
Basically, yes. The idea is to make the pcb only as big as the screen to minimize space.
I removed the screen from the pcb, removed the sd card reader, cut the excess with a dremel and placed the screen back over the pins.
You need screens with the flex cable going through the pcb, the other designs don't allow you to move the screen towards the pins.

**Comment by SaLuci** [comment]
Thank you
